// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/system/dao/internal"
)

// pushChannelCustomWebhookDao is the data access object for the table push_channel_custom_webhook.
// You can define custom methods on it to extend its functionality as needed.
type pushChannelCustomWebhookDao struct {
	*internal.PushChannelCustomWebhookDao
}

var (
	// PushChannelCustomWebhook is a globally accessible object for table push_channel_custom_webhook operations.
	PushChannelCustomWebhook = pushChannelCustomWebhookDao{internal.NewPushChannelCustomWebhookDao()}
)

// Add your custom methods and functionality below.
