// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/system/dao/internal"
)

// pushChannelWebhookDao is the data access object for the table push_channel_webhook.
// You can define custom methods on it to extend its functionality as needed.
type pushChannelWebhookDao struct {
	*internal.PushChannelWebhookDao
}

var (
	// PushChannelWebhook is a globally accessible object for table push_channel_webhook operations.
	PushChannelWebhook = pushChannelWebhookDao{internal.NewPushChannelWebhookDao()}
)

// Add your custom methods and functionality below.
