// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/system/dao/internal"
)

// pushChannelDao is the data access object for the table push_channel.
// You can define custom methods on it to extend its functionality as needed.
type pushChannelDao struct {
	*internal.PushChannelDao
}

var (
	// PushChannel is a globally accessible object for table push_channel operations.
	PushChannel = pushChannelDao{internal.NewPushChannelDao()}
)

// Add your custom methods and functionality below.
