// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/system/dao/internal"
)

// pushChannelEmailDao is the data access object for the table push_channel_email.
// You can define custom methods on it to extend its functionality as needed.
type pushChannelEmailDao struct {
	*internal.PushChannelEmailDao
}

var (
	// PushChannelEmail is a globally accessible object for table push_channel_email operations.
	PushChannelEmail = pushChannelEmailDao{internal.NewPushChannelEmailDao()}
)

// Add your custom methods and functionality below.
