// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/system/dao/internal"
)

// sysLogsDao is the data access object for the table sys_logs.
// You can define custom methods on it to extend its functionality as needed.
type sysLogsDao struct {
	*internal.SysLogsDao
}

var (
	// SysLogs is a globally accessible object for table sys_logs operations.
	SysLogs = sysLogsDao{internal.NewSysLogsDao()}
)

// Add your custom methods and functionality below.
