// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/system/dao/internal"
)

// sysSettingsDao is the data access object for the table sys_settings.
// You can define custom methods on it to extend its functionality as needed.
type sysSettingsDao struct {
	*internal.SysSettingsDao
}

var (
	// SysSettings is a globally accessible object for table sys_settings operations.
	SysSettings = sysSettingsDao{internal.NewSysSettingsDao()}
)

// Add your custom methods and functionality below.
