// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/stream/dao/internal"
)

// anchorInfoDao is the data access object for the table anchor_info.
// You can define custom methods on it to extend its functionality as needed.
type anchorInfoDao struct {
	*internal.AnchorInfoDao
}

var (
	// AnchorInfo is a globally accessible object for table anchor_info operations.
	AnchorInfo = anchorInfoDao{internal.NewAnchorInfoDao()}
)

// Add your custom methods and functionality below.
