// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/stream/dao/internal"
)

// anchorInfoHistoryDao is the data access object for the table anchor_info_history.
// You can define custom methods on it to extend its functionality as needed.
type anchorInfoHistoryDao struct {
	*internal.AnchorInfoHistoryDao
}

var (
	// AnchorInfoHistory is a globally accessible object for table anchor_info_history operations.
	AnchorInfoHistory = anchorInfoHistoryDao{internal.NewAnchorInfoHistoryDao()}
)

// Add your custom methods and functionality below.
