// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/stream/dao/internal"
)

// liveHistoryDao is the data access object for the table live_history.
// You can define custom methods on it to extend its functionality as needed.
type liveHistoryDao struct {
	*internal.LiveHistoryDao
}

var (
	// LiveHistory is a globally accessible object for table live_history operations.
	LiveHistory = liveHistoryDao{internal.NewLiveHistoryDao()}
)

// Add your custom methods and functionality below.
