// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/stream/dao/internal"
)

// liveCookieDao is the data access object for the table live_cookie.
// You can define custom methods on it to extend its functionality as needed.
type liveCookieDao struct {
	*internal.LiveCookieDao
}

var (
	// LiveCookie is a globally accessible object for table live_cookie operations.
	LiveCookie = liveCookieDao{internal.NewLiveCookieDao()}
)

// Add your custom methods and functionality below.
