// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/stream/dao/internal"
)

// liveRoomInfoDao is the data access object for the table live_room_info.
// You can define custom methods on it to extend its functionality as needed.
type liveRoomInfoDao struct {
	*internal.LiveRoomInfoDao
}

var (
	// LiveRoomInfo is a globally accessible object for table live_room_info operations.
	LiveRoomInfo = liveRoomInfoDao{internal.NewLiveRoomInfoDao()}
)

// Add your custom methods and functionality below.
