// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/stream/dao/internal"
)

// liveManageDao is the data access object for the table live_manage.
// You can define custom methods on it to extend its functionality as needed.
type liveManageDao struct {
	*internal.LiveManageDao
}

var (
	// LiveManage is a globally accessible object for table live_manage operations.
	LiveManage = liveManageDao{internal.NewLiveManageDao()}
)

// Add your custom methods and functionality below.
