// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/media/dao/internal"
)

// fileCheckTaskDao is the data access object for the table file_check_task.
// You can define custom methods on it to extend its functionality as needed.
type fileCheckTaskDao struct {
	*internal.FileCheckTaskDao
}

var (
	// FileCheckTask is a globally accessible object for table file_check_task operations.
	FileCheckTask = fileCheckTaskDao{internal.NewFileCheckTaskDao()}
)

// Add your custom methods and functionality below.
