// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/shichen437/gowlive/internal/app/media/dao/internal"
)

// fileSyncTaskDao is the data access object for the table file_sync_task.
// You can define custom methods on it to extend its functionality as needed.
type fileSyncTaskDao struct {
	*internal.FileSyncTaskDao
}

var (
	// FileSyncTask is a globally accessible object for table file_sync_task operations.
	FileSyncTask = fileSyncTaskDao{internal.NewFileSyncTaskDao()}
)

// Add your custom methods and functionality below.
